; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	esp32cam
src_dir = .
include_dir = .

[env]
build_flags = -Wall -Wextra
; monitor_filters = time

[env:esp32cam]
; Lock version to 6.7.0 as that is
; Arduino v2.0.16 (based on IDF v4.4.7)
; which is the latest version based
; on IDF v4. We can not use IDF v5.
platform = espressif32 @ 6.7.0
board = esp32cam
framework = arduino
lib_deps = ${env.lib_deps}
build_flags =
	-std=c++17
	${env.build_flags}
monitor_speed = 115200
monitor_echo = yes

[env:esp32wrover]
; Lock version to 6.7.0 as that is
; Arduino v2.0.16 (based on IDF v4.4.7)
; which is the latest version based
; on IDF v4. We can not use IDF v5.
platform = espressif32 @ 6.7.0
board = esp32dev
board_build.partitions = huge_app.csv
framework = arduino
lib_deps = ${env.lib_deps}
build_flags =
	-std=c++17
	${env.build_flags}
monitor_speed = 115200
monitor_echo = yes
